/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Keypad_1_Keypad1.h"
#include "LCD.h"
#include "isr_press.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "Encoder_aliases.h"
#include "Encoder.h"
#include "timer_clock.h"
#include "Timer.h"
#include "isr_1.h"
#include "isr_Encoder.h"
#include "PWM.h"
#include "salida_aliases.h"
#include "salida.h"
#include "cruce_por_cero_aliases.h"
#include "cruce_por_cero.h"
#include "num_control_aliases.h"
#include "num_control.h"
#include "Keypad_1_Status_Reg.h"
#include "Keypad_1_Column_aliases.h"
#include "Keypad_1_Row_aliases.h"
#include "Keypad_1_Clock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

